server:
  port: 8191

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/denofcoders/config-server-settings
          search-paths:
            - 'service-config/*service'



